# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "ruby-slack-openai-chat-bot"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "ruby-slack-openai-chat-bot-development"
s3_prefix = "ruby-slack-openai-chat-bot-development"
region = "us-east-1"
image_repositories = []

[production.deploy.parameters]
stack_name = "ruby-slack-openai-chat-bot-production"
s3_prefix = "ruby-slack-openai-chat-bot-production"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
