version = 0.1
[default.deploy.parameters]
stack_name = "slack-bot-production"
resolve_s3 = true
s3_prefix = "slack-bot-production"
region = "us-east-1"
profile = "AdministratorAccess-330731243300"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\" AwsResourcePrefix=\"slack-bot\" SlackAppId=\"A05FL341GBT\" SlackAppAccessToken=\"xoxb-110349497378-5517515034786-JKs1izFgT1GZjtyV98gN8xC6\" OpenAiApiToken=\"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\""
image_repositories = []
