AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  OpenAI-powered chat bot for Slack.

Parameters:
  Environment:
    Description: 'Name of runtime environment: development, test, staging, production'
    Type: 'String'
    Default: 'development'
  AwsResourcePrefix:
    Description: 'The name prefix for resources related to the app.'
    Type: 'String'
    Default: 'slack-bot'
  SlackAppId:
    Description: 'Your App ID for your Slack app.'
    Type: 'String'
  SlackAppAccessToken:
    Description: 'Your "Bot User OAuth Token" for your Slack app.'
    Type: 'String'
  OpenAiApiToken:
    Description: 'Your API token from OpenAI.'
    Type: 'String'

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub
        - '${Prefix}-dependencies-layer-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      Description: A layer containing Ruby gem dependencies.
      ContentUri: dependencies-layer/.
      CompatibleRuntimes:
        - ruby2.7
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: ruby2.7

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Description: 'Prod stage'
      TracingEnabled: true
      MethodSettings:
      - HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: '/*'
        MetricsEnabled: true
        DataTraceEnabled: true

  APIGatewayHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub
        - '${Prefix}-api-gateway-handler-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      CodeUri: ./
      Handler: api_gateway.api_gateway_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          SQS_QUEUE_URL: !Ref SlackEventsQueue
          KEY_VALUE_STORE_TABLE: !Ref KeyValueStoreDynamoDBTable
          SLACK_APP_ID: !Ref SlackAppId
          SLACK_APP_ACCESS_TOKEN: !Ref SlackAppAccessToken
          OPEN_AI_API_TOKEN: !Ref OpenAiApiToken
      Tracing: Active
      Events:
        EventsAPI:
          Type: Api 
          Properties:
            RestApiId: 
                !Ref APIGateway
            Path: /events
            Method: post
      Policies:
        - Statement:
          - Sid: SQSSendMessagePolicy
            Effect: Allow
            Action:
            - sqs:SendMessage
            Resource: !GetAtt SlackEventsQueue.Arn
          - Sid: DynamoDBCrudPolicy
            Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Resource: !GetAtt KeyValueStoreDynamoDBTable.Arn

  SlackEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - '${Prefix}-events-queue-${Environment}.fifo'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 300

  SlackEventsAPIHandlerHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub
        - '${Prefix}-slack-event-processor-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      CodeUri: ./
      Handler: sqs_message_processor.sqs_message_processor_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment: 
        Variables:
          ENVIRONMENT: !Ref Environment
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          KEY_VALUE_STORE_TABLE: !Ref KeyValueStoreDynamoDBTable
          SLACK_CONVERSATION_HISTORY_TABLE: !Ref SlackConversationHistoryTable
          SLACK_APP_ID: !Ref SlackAppId
          SLACK_APP_ACCESS_TOKEN: !Ref SlackAppAccessToken
          OPEN_AI_API_TOKEN: !Ref OpenAiApiToken
      Tracing: Active
      Events:
        SlackEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SlackEventsQueue.Arn
      Policies:
      - Statement:
        - Sid: DynamoDBCrudPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: 
          - !GetAtt KeyValueStoreDynamoDBTable.Arn
          - !GetAtt SlackConversationHistoryTable.Arn

  KeyValueStoreDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - '${Prefix}-key-value-store-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  SlackConversationHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - '${Prefix}-slack-conversation-history-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
        - AttributeName: ts
          AttributeType: N
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
        - AttributeName: ts
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
Outputs:
  SlackEventsAPIHandlerEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Slack Events API handler function."
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/events/"