AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ruby-slack-openai-chat-bot

  Sample SAM Template for ruby-slack-openai-chat-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  SlackEventsApiHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lib/
      Handler: bot.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Events:
        # For the Slack Events API handler endpoint.
        EventsAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events
            Method: post
      Policies:
      - Statement:
        - Sid: SSMDescribeParametersPolicy
          Effect: Allow
          Action:
          - ssm:DescribeParameters
          Resource: '*'
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          Resource: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackEventsApiEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Slack Events API handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events/"
  SlackEventsApiHandlerFunction:
    Description: "Slack Events API handler Lambda Function ARN"
    Value: !GetAtt SlackEventsApiHandlerFunction.Arn
  SlackEventsApiFunctionIamRole:
    Description: "Implicit IAM Role created for Slack Events API handler function"
    Value: !GetAtt SlackEventsApiHandlerFunctionRole.Arn
