AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  OpenAI-powered chat bot for Slack.

Parameters:
  Environment:
    Description: 'Name of runtime environment: development, test, staging, production'
    Type: 'String'
    Default: 'development'
  AwsResourceName:
    Description: 'A title-cased name of the bot service.'
    Type: 'String'
    Default: 'Slack Bot'
  AwsResourcePrefix:
    Description: 'The name prefix for resources related to the app.'
    Type: 'String'
    Default: 'slack-bot'
  SlackAppId:
    Description: 'Your App ID for your Slack app.'
    Type: 'String'
  SlackAppAccessToken:
    Description: 'Your "Bot User OAuth Token" for your Slack app.'
    Type: 'String'
  OpenAiApiToken:
    Description: 'Your API token from OpenAI.'
    Type: 'String'

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub
        - '${Prefix}-dependencies-layer-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      Description: A layer containing Ruby gem dependencies.
      ContentUri: dependencies-layer/.
      CompatibleRuntimes:
        - ruby2.7
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: ruby2.7

  OpenAiApiTokenSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub
        - '${Prefix}-openai-api-token-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      SecretString: !Ref OpenAiApiToken
  
  SlackAppAccessTokenSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties: 
      Name: !Sub
        - '${Prefix}-slack-app-access-token-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      SecretString: !Ref SlackAppAccessToken

  SystemPromptSSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties: 
      Name: !Sub
        - '${Prefix}-system-prompt-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      Type: String
      Value: ' '

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Description: 'Prod stage'
      TracingEnabled: true
      MethodSettings:
      - HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: '/*'
        MetricsEnabled: true
        DataTraceEnabled: true

  APIGatewayHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub
        - '${Prefix}-api-gateway-handler-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      CodeUri: ./
      Handler: api_gateway.api_gateway_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          AWS_RESOURCE_PREFIX: !Ref AwsResourcePrefix
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          SQS_QUEUE_URL: !Ref SlackEventsQueue
          KEY_VALUE_STORE_TABLE: !Ref KeyValueStoreDynamoDBTable
      Tracing: Active
      Events:
        EventsAPI:
          Type: Api 
          Properties:
            RestApiId: 
              !Ref APIGateway
            Path: /events
            Method: post
      Policies:
        - Statement:
          - Sid: SQSSendMessagePolicy
            Effect: Allow
            Action:
            - sqs:SendMessage
            Resource: !GetAtt SlackEventsQueue.Arn
          - Sid: DynamoDBCrudPolicy
            Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Resource: !GetAtt KeyValueStoreDynamoDBTable.Arn
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:PutParameter
            Resource:
            - !Sub
              - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Prefix}-system-prompt-${Environment}'
              - Prefix: !Ref AwsResourcePrefix
                Environment: !Ref Environment
          - Sid: SecretsManagerGetSecretValuePolicy
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - !Sub
                - 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Prefix}-openai-api-token-${Environment}-*'
                - Prefix: !Ref AwsResourcePrefix
                  Environment: !Ref Environment
              - !Sub
                - 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Prefix}-slack-app-access-token-${Environment}-*'
                - Prefix: !Ref AwsResourcePrefix
                  Environment: !Ref Environment

  SlackEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - '${Prefix}-events-queue-${Environment}.fifo'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 300

  SlackEventsAPIHandlerHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub
        - '${Prefix}-slack-event-processor-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      CodeUri: ./
      Handler: sqs_message_processor.sqs_message_processor_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment: 
        Variables:
          ENVIRONMENT: !Ref Environment
          AWS_RESOURCE_PREFIX: !Ref AwsResourcePrefix
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          KEY_VALUE_STORE_TABLE: !Ref KeyValueStoreDynamoDBTable
          SLACK_CONVERSATION_HISTORY_TABLE: !Ref SlackConversationHistoryTable
          SLACK_MESSAGES_RECEIVED_METRIC: !Sub
            - "${Namespace}::Slack Messages Received - ${Environment}"
            - Namespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
              Environment: !Ref Environment
          SLACK_MESSAGES_SENT_METRIC: !Sub
            - "${Namespace}::Slack Messages Sent - ${Environment}"
            - Namespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
              Environment: !Ref Environment
          OPEN_AI_CHAT_API_METRIC: !Sub
            - "${Namespace}::Open AI Chat API Responses - ${Environment}"
            - Namespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
              Environment: !Ref Environment
          FUNCTION_RESPONSES_METRIC: !Sub
            - "${Namespace}::Function Responses - ${Environment}"
            - Namespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
              Environment: !Ref Environment
      Tracing: Active
      Events:
        SlackEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SlackEventsQueue.Arn
      Policies:
      - Statement:
        - Sid: DynamoDBCrudPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: 
          - !GetAtt KeyValueStoreDynamoDBTable.Arn
          - !GetAtt SlackConversationHistoryTable.Arn
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameter
          - ssm:PutParameter
          Resource: 
          - !Sub
            - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Prefix}-system-prompt-${Environment}'
            - Prefix: !Ref AwsResourcePrefix
              Environment: !Ref Environment
        - Sid: SecretsManagerGetSecretValuePolicy
          Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 
            - !Sub
              - 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Prefix}-openai-api-token-${Environment}-*'
              - Prefix: !Ref AwsResourcePrefix
                Environment: !Ref Environment
            - !Sub
              - 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Prefix}-slack-app-access-token-${Environment}-*'
              - Prefix: !Ref AwsResourcePrefix
                Environment: !Ref Environment
        - Sid: CloudWatchGetMetricStatisticsProperty
          Effect: Allow
          Action:
            - cloudwatch:GetMetricStatistics
          Resource: "*"

  KeyValueStoreDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub
        - '${Prefix}-key-value-store-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SlackConversationHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub
        - '${Prefix}-slack-conversation-history-${Environment}'
        - Prefix: !Ref AwsResourcePrefix
          Environment: !Ref Environment
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
        - AttributeName: ts
          AttributeType: N
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
        - AttributeName: ts
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SlackMessagesReceivedMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AwsResourcePrefix}-slack-event-processor-${Environment}'
      FilterPattern: "Slack message event"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
          MetricName: !Sub
            - "Slack Messages Received - ${Environment}"
            - Environment: !Ref Environment

  SlackMessagesSentMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: !Sub '/aws/lambda/${AwsResourcePrefix}-slack-event-processor-${Environment}'
        FilterPattern: "Sent message to Slack"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
            MetricName: !Sub
              - "Slack Messages Sent - ${Environment}"
              - Environment: !Ref Environment

  OpenAiChatMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AwsResourcePrefix}-slack-event-processor-${Environment}'
      FilterPattern: "OpenAI chat API response"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
          MetricName: !Sub
            - "Open AI Chat API Responses - ${Environment}"
            - Environment: !Ref Environment
  
  FunctionResponsesMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AwsResourcePrefix}-slack-event-processor-${Environment}'
      FilterPattern: "Function response"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
          MetricName: !Sub
            - "Function Responses - ${Environment}"
            - Environment: !Ref Environment

  BotDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub
        - "${Name}-${Environment}"
        - Name: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]
          Environment: !Ref Environment
      DashboardBody: !Sub
        - |
            {
              "widgets": [
                {
                  "type": "metric",
                  "x": 0,
                  "y": 0,
                  "width": 24,
                  "height": 6,
                  "properties": {
                    "metrics": [
                      [
                        "${Namespace}", 
                        "Slack Messages Received - ${Environment}"
                      ],
                      [
                        "${Namespace}", 
                        "Slack Messages Sent - ${Environment}"
                      ],
                      [
                        "${Namespace}", 
                        "Open AI Chat API Responses - ${Environment}"
                      ],
                      [
                        "${Namespace}", 
                        "Function Responses - ${Environment}"
                      ]
                    ],
                    "view": "timeSeries",
                    "stacked": false,
                    "region": "${AWS::Region}",
                    "period": 300,
                    "title": "Activity",
                    "stat": "Sum"
                  }
                }
              ]
            }
        - Namespace: !Join [ '', !Split [ ' ', !Ref AwsResourceName ] ]

Outputs:
  ApiGatewayApiEndpoint:
    Description: 'API Gateway API endpoint URL for Prod stage for Slack events'
    Value: !Sub 'https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/events'
