AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ruby-slack-openai-chat-bot

  Sample SAM Template for ruby-slack-openai-chat-bot

Parameters:
  ENVIRONMENT:
    Description: 'development, test, staging, production'
    Type: 'String'
    Default: 'development'

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  SlackEventsAPIHandlerHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: sqs_message_processor.sqs_message_processor_lambda_handler
      Runtime: ruby2.7
      Environment: 
        Variables:
          ENVIRONMENT: !Ref ENVIRONMENT
      Architectures:
        - x86_64
      Events:
        SlackEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SlackEventsQueue.Arn
      Policies:
      - Statement:
        - Sid: SSMDescribeParametersPolicy
          Effect: Allow
          Action:
          - ssm:DescribeParameters
          Resource: '*'
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          Resource: '*'
  
  SlackEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
          VisibilityTimeout: 300

  APIGatewayHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: api_gateway.api_gateway_lambda_handler
      Runtime: ruby2.7
      Environment: 
        Variables:
          ENVIRONMENT: !Ref ENVIRONMENT
      Architectures:
        - x86_64
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref SlackEventsQueue
      Events:
        EventsAPI:
          Type: Api 
          Properties:
            Path: /events
            Method: post
      Policies:
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: '*'
          - Sid: SQSSendMessagePolicy
            Effect: Allow
            Action:
            - sqs:SendMessage
            Resource: !GetAtt SlackEventsQueue.Arn

Outputs:
  SlackEventsAPIHandlerEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Slack Events API handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events/"