AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ruby-slack-openai-chat-bot

  Sample SAM Template for ruby-slack-openai-chat-bot

Parameters:
  ENVIRONMENT:
    Description: 'development, test, staging, production'
    Type: 'String'
    Default: 'development'

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:  !Sub
        - 'ruby-slack-openai-chat-bot-dependencies-layer-${Environment}'
        - Environment: !Ref ENVIRONMENT
      Description: A layer containing Ruby gem dependencies.
      ContentUri: dependencies-layer/.
      CompatibleRuntimes:
        - ruby2.7
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: ruby2.7

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Description: 'Prod stage'
      TracingEnabled: true
      MethodSettings:
      - HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: '/*'
        MetricsEnabled: true
        DataTraceEnabled: true

  APIGatewayHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: api_gateway.api_gateway_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref ENVIRONMENT
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          SQS_QUEUE_URL: !Ref SlackEventsQueue
          KEY_VALUE_STORE: !Ref KeyValueStoreDynamoDBTable
      Tracing: Active
      Events:
        EventsAPI:
          Type: Api 
          Properties:
            RestApiId: 
                !Ref APIGateway
            Path: /events
            Method: post
      Policies:
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: '*'
          - Sid: SQSSendMessagePolicy
            Effect: Allow
            Action:
            - sqs:SendMessage
            Resource: !GetAtt SlackEventsQueue.Arn
          - Sid: DynamoDBCrudPolicy
            Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Resource: !GetAtt KeyValueStoreDynamoDBTable.Arn

  SlackEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - 'ruby_slack_openai_chat_bot_events_queue_${Environment}.fifo'
        - Environment: !Ref ENVIRONMENT
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 300

  SlackEventsAPIHandlerHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./
      Handler: sqs_message_processor.sqs_message_processor_lambda_handler
      Runtime: ruby2.7
      Layers:
        - !Ref DependenciesLayer
      Architectures:
        - x86_64
      Environment: 
        Variables:
          ENVIRONMENT: !Ref ENVIRONMENT
          RUBYLIB: /opt/ruby/lib
          BUNDLE_GEMFILE: /opt/ruby/lib/Gemfile
          GEM_PATH: /opt/ruby/lib/vendor/bundle/ruby/2.7.0
          KEY_VALUE_STORE: !Ref KeyValueStoreDynamoDBTable
      Tracing: Active
      Events:
        SlackEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SlackEventsQueue.Arn
      Policies:
      - Statement:
        - Sid: SSMDescribeParametersPolicy
          Effect: Allow
          Action:
          - ssm:DescribeParameters
          Resource: '*'
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          Resource: '*'
        - Sid: DynamoDBCrudPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: !GetAtt KeyValueStoreDynamoDBTable.Arn

  KeyValueStoreDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub
        - 'ruby-slack-openai-chat-bot-key-value-store-${Environment}'
        - Environment: !Ref ENVIRONMENT
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
  
Outputs:
  SlackEventsAPIHandlerEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Slack Events API handler function"
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/events/"