name: Ruby

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: dependencies-layer
        key: bundle-use-ruby-${{ matrix.ruby-version }}-${{ hashFiles('dependencies-layer/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.ruby-version }}-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Bundle install
      run: |
        bundle install --gemfile=$GITHUB_WORKSPACE/dependencies-layer/Gemfile --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake spec
